-- {{ config(materialized='table') }}


-- WITH dest_table AS  (
--     SELECT *, row_number() over(partition by id ORDER BY DAG_TS desc) AS rn
--     FROM {{ ref("history") }}
-- ),

-- incl_deletes AS (
--     SELECT
--         COALESCE(CAST(src.id AS STRING), CAST(dest.id AS STRING)) AS id,
--         src.* EXCEPT(id),
--         IF(src.id IS NULL, TRUE, FALSE) AS IS_DELETED
--     FROM {{ source("raw-sbx", "employees")}} AS src
--     FULL OUTER JOIN (
--     SELECT * EXCEPT(rn)
--     FROM dest_table
--     WHERE rn = 1
--     ) AS dest
--     ON CAST(src.id AS STRING) = CAST(dest.id AS STRING)
-- ),

-- incl_row_hash AS (
--     SELECT
--     CAST(id AS STRING) as id,
--     ip_address,
--     ssn,
--     email,
--     address_longitude,
--     birth_date,
--     start_date,
--     license_plate,
--     username,
--     city,
--     position,
--     department,
--     salary,
--     bonus,
--     credit_card_number,
--     SHA256(CONCAT(
--                 IFNULL(CAST(ip_address AS STRING), "$"),
--                 "$",
--                 IFNULL(CAST(ssn AS STRING), "$"),
--                 "$",
--                 IFNULL(CAST(email AS STRING), "$"),
--                 "$",
--                 IFNULL(CAST(address_longitude AS STRING), "$"),
--                 "$",
--                 IFNULL(CAST(birth_date AS STRING), "$"),
--                 "$",
--                 IFNULL(CAST(start_date AS STRING), "$"),
--                 "$",
--                 IFNULL(CAST(license_plate AS STRING), "$"),
--                 "$",
--                 IFNULL(CAST(username AS STRING), "$"),
--                 "$",
--                 IFNULL(CAST(city AS STRING), "$"),
--                 "$",
--                 IFNULL(CAST(position AS STRING), "$"),
--                 "$",
--                 IFNULL(CAST(department AS STRING), "$"),
--                 "$",
--                 IFNULL(CAST(salary AS STRING), "$"),
--                 "$",
--                 IFNULL(CAST(bonus AS STRING), "$"),
--                 "$",
--                 IFNULL(CAST(credit_card_number AS STRING), "$")
--                 )
--     ) AS ROW_HASH,
--     FROM incl_deletes
-- )
-- SELECT
--     '{{ run_id }}' AS DAG_RUN,
--     TIMESTAMP('{{ ts }}') AS DAG_TS,
--     *
-- FROM incl_row_hash
-- WHERE ROW_HASH NOT IN (SELECT ROW_HASH FROM dest_table)

